### ISSUE TITLE
Web interface does not load with HA version 99.2

### ISSUE THREAD

**Issue by matthewcky2k** [thanksmister/wallpanel-android#123]
**Describe the bug**
Web interface does not load with HA version 99.2 it seems to hang on the 'Initializing'  screen? worked fine on version 98.5

**To Reproduce**
Open Wall panel or tap on dashboard 

**Expected behavior**
To load the Authentication screen and continue

**Screenshots**
https://imgur.com/hcHdr8i

**Smartphone (please complete the following information):**
 - Device: Fire HD 10 (2017)
 - OS: Fire OS 5.3.6.8
 - Browser Stock Browser and chrome
 - Version 

**Additional context**

**Comment by thanksmister** [comment]
The application has a limitation when viewing web pages because internally the Android application uses WebView to render web pages, it is not the same as using Google Chrome browser.  If you cannot render the webpage, your only option is to update the webpage code, the internal WebView component of Android cannot be modified or made to render pages differently.

**Comment by fiLLLip** [comment]
For what it's worth, I got a similar problem with Mosaic webapp on LogicMachine, running on Android 6.0. It works fine in Chrome there as well, but not in wallpanel. Looks like something locks up when launching the application. My guess is something javascript related.
