### ISSUE TITLE
App closes unexpectedly after Android WebView upgrade

### ISSUE THREAD

**Issue by dogghy14** [thanksmister/wallpanel-android#128]
App closes unexpectedly on my Nexus 7 3G (tilapia) after updating to version 77.0.3865.116 of Android System WebView.
Settings view works correctly.

**Comment by thanksmister** [comment]
I tested on an Nexus 5 with Android 10 and WebView 77.0.3865.116.   I could find no issues, no crashes, no errors. I tested using the latest build on the Google Play store with MQTT setup pointing to my HA installation.   I have no crash reports at all for WallPanel v0.8.8 Build 6 (8806).  So at this time, I am not sure what is the issue.  If there were an app crash, I would receive a report.   Maybe it is a permission issue, maybe you can uninstall and reinstall the app again.

**Comment by thanksmister** [comment]
It could also be something on the the page you are trying to render or a possible security issue on the webpage.   I know that Android 9 required additional permissions to use the WebView.

**Comment by dogghy14** [comment]
Android crash reports no opens when app crashes.
I'm using official Nexus build of Android 5.1.1.

Logcat attached.

[logcat.txt](https://github.com/thanksmister/wallpanel-android/files/3718210/logcat.txt)

Many thanks!
A.

**Comment by thanksmister** [comment]
I loaded the application on my old Asus Nexus running Android 5.1.1 and immediately received the same results as you did.

D/BrowserActivityNative: Mozilla/5.0 (Linux; Android 5.1.1; Nexus 7 Build/LMY47V; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Safari/537.36
D/BrowserActivityNative: loadUrl http://192.168.86.228:8123
E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
F/libc    ( 3609): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 3609 (r.iot.wallpanel)

My guess is that either the WebView is causing the issue or it was the requirement that Google made that all applications must now support 64 bit .  They break the application into different parts for each kind of processor and this may be a support issue. 

For now, I recommend you download one of the previous APK files from the release section for this project and use that until I can discover or if I discover the issue and a possible solution for older devices.  I was able to run the app fine on Android 6 and above.  The application no longer supports Android 4 devices, so that leaves just Android 5 devices which are now experiencing this issue.

**Comment by dogghy14** [comment]
Ok, I will.

Thanks again

**Comment by thanksmister** [comment]
If you crash with the previous APK versions then its the WebView.  If you do not crash, it must be the 64 bit code support change.

**Comment by thanksmister** [comment]
I pushed out a fix in v0.8.8-beta.7 which will be available in the Google Play store soon.   I reverted the RenderScript library to an older version, the camera features should still work.

**Comment by dogghy14** [comment]
Yeah, thanks mister!
I'll give you a feedback as soon as I've tried.

A.

**Comment by thanksmister** [comment]
@dogghy14 any success?

**Comment by dogghy14** [comment]
Hi!
My adsl is working again, so I was able to try the new version of the app and it works correctly. 

Thanks!
