### ISSUE TITLE
Face Detection Fine Tuning

### ISSUE THREAD

**Issue by lweberru** [thanksmister/wallpanel-android#149]
Currently the face detection works very well. But it detects faces so good, that the panel is always "awake" even I am just sitting in my room and looking in direction of the panel only wanting to see the nice pictures of my daylight screensaver. 
It would be cool to get some kind of fine tuning to decide when the display should be awakened, like the size of the face (distance of the face).
Regards
Lukas

**Comment by thanksmister** [comment]
We do not have that option, the face detection library works like that by design.   I recommend using motion detection feature instead or relocating the panel.  It is set to use large faces, so it should not detect faces across the room.   There are no other options besides big or small faces with the Google ML library that runs locally.

**Comment by lweberru** [comment]
Thanks for answering. But with motion detection I have the same issue, or is it possible to fine tune the motion detection, to not trigger on move 2+ meters away? 
Regards
Lukas

**Comment by thanksmister** [comment]
Distance no... the motion detection works based on the amount of change in the image which you can adjust in the application, but it cannot detect distance.  Try using the settings in the app to adjust the sensitivity of the motion detection.
