### ISSUE TITLE
Minimizing w/ Motion & Face Detection

### ISSUE THREAD

**Issue by TheAlphaLaw** [thanksmister/wallpanel-android#151]
**Platform:** Home Assistant w/ Hadashboard
**Tablets:** Amazon HD8 2018
- Tablet ads/Amazon garbage removed.

Often (but variable) when a tablet detects motion or a face, it will minimize Wallpanel and move to the Android home screen. The app does not crash, it remains running and can resume previous location when selected from notification bar. 

I've also seen this happen when restarting my Home Assistant instance also.

**Comment by TheAlphaLaw** [comment]
Is there possibly a way to restart the app when minimized or closed/crashed? I really love this app and don't want to move to Fully Kiosk (hate it), but this issue is constantly happening.

**Comment by pkatzu** [comment]
I'm sur you can use this [app](https://llamalab.com/automate/) or Tasker.

**Comment by TheAlphaLaw** [comment]
@pkatzu 

Great, will give it a shot. Do you know if this project has been abandoned?

**Comment by pkatzu** [comment]
I've just createad a flow in Automate that starts this app when my tablet starts _and_ connected to WiFi (as if we enable start on boot, the appsometimes fails to connect as WiFi is still not up).

I don't think the project has been abandoned based on the owner's commits.
People have their things to do sometimes ;)

**Comment by thanksmister** [comment]
@TheAlphaLaw please be respectful on this projects issue tracker.  Just because your specific problem has not been addressed does not mean the entire project has been abandoned.   Amazon tablets are notorious for having quirks other tablets do not.  I also have an Amazon tablet and it does the same behavior and nothing can be done about it.   Why don't you just stop using the face detection feature on this brand of tablet.   I am closing this for now since there is nothing I can do to resolve your issue.
