### ISSUE TITLE
Is hardware acceleration really disabled?

### ISSUE THREAD

**Issue by nagyrobi** [thanksmister/wallpanel-android#172]
On my MT8127-based tablet, running Android 5.0.1, and on another Cortex-A7-based device running Android 7.1.2, Home Assistant's Lovelace is very laggy using WallPanel: Switches move slowly, pages change slowly etc. animations are horrible.

Tried changing the hardware acceleration toggle but no difference is observed.
The same Lovelace interface displayed on Firefox or Chrome browser appears smooth and well.

Changed to WallPanel Legacy. This doesn't have a hardware acceleration option, but Home Assistant's Lovelace interface is a whole lot smoother, using WebView engine! (Using Crosswalk doesn't even load Lovelace, see [report](https://github.com/thanksmister/wallpanel-android-legacy/issues/4).)

This makes me wonder, what's the difference between WallPanel standard and WallPanel Legacy, when both use WebView, that makes the legacy version show Lovelace so much smoother? Maybe the hardware acceleration option isn't really ever disabled on the standard version?

**Comment by thanksmister** [comment]
Well, you can check the code, hardware acceleration is not enabled by default.  Here is the specific code for hardware acceleration: 

```
if(configuration.hardwareAccelerated && Build.VERSION.SDK_INT > Build.VERSION_CODES.LOLLIPOP_MR1) {
            window.setFlags(WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED, WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED)
        }
```

You have to have this setting on in the application settings and also you must be running greater Android 6.0 or greater.   

This project does not use a web browser, so comparing how Lovelace renders in a browser is not valid.  The application uses the Android WebView component to render webpages, this uses a subset of Chrome.  The version of WebView you have depend on which version of Android  you have available on your device.  You may be able to update WebView from Google Play.

The legacy version offers Crosswalk, which is no longer a supported project and so that application is no longer supported.  If you are running Android 5, then the legacy version may be a better option for you.   WallPanel uses WebView, the legacy version offers Crosswalk as an option.  

The issue really is Lovelace and its compatibility with older web standards.  Some components in Lovelace might not work in WallPanel.  You can create a new desktop in Lovelace and add each component one by one until it breaks.  This will give you an idea of what you can display in the application.

**Comment by nagyrobi** [comment]
The question is:
- WallPanel (standard) with WebView creates laggy Lovelace
- WallPanel (legacy) with WebView creates smooth Lovelace
On the same units. Why?

**Comment by thanksmister** [comment]
The only difference is they target different OS version, legacy does not target the current version of Android and it uses libraries to make it backward compatible.   This could be the reason for the difference, the app is running with different compatibility libraries on your device.   That was the reason why the project split, the new version started losing compatibility with older devices.  The Google Play store should list that this is not compatible with devices running less than Android 6, but it incorrectly says compatible back to Android 4.4.  This is not true because the Paho MQTT library had dependencies that do not work that far back and causes crashes.
