### ISSUE TITLE
Add Kiosk Features

### ISSUE THREAD

**Issue by thanksmister** [thanksmister/wallpanel-android#190]
Add the ability to run WallPanel as the Home application on Android devices and options to block button controls.  This gives WallPanel a kiosk effect, blocking others from access the device.  In addition we could add pincode access to the settings to prevent others from modifying WallPanel.

**Comment by thanksmister** [comment]
This is another question about using other apps or power tools like Termux to possibly achieve this.  The most valuable feature to me of a wall panel or dashboard is a kiosk feature.  Some Android apps try to do this, but always it is always a little clunky or they charge because they want to manage the entire device.

**Comment by leikoilja** [comment]
Achieved that with a Home Assistant's [custom-header](https://github.com/maykar/custom-header) package. Setup a new user for android tablet and enabled kiosk mode with a tons of restrictions, so the WallPanel just shows one screen all the time.

Thanks for the app, @thanksmister

**Comment by hwcconde** [comment]
I'm using WallPanel happily but I also find that the ability to press back button and change settings is also making my kids really happy...
Is any way to PIN lock the settings, or best as this thread says locking the buttons?

**Comment by thanksmister** [comment]
@hwcconde Not in this current version.  I am working on a new version of the application which will have this feature.  Thanks for the feedback.

**Comment by t0bse** [comment]
i am using this one

https://github.com/maykar/kiosk-mode

**Comment by Din-BH** [comment]
@thanksmister - First of all great thanks for this App - really great work! I am using the kiosk-more like t0bse, but I am running into cases where the app jumps back from the Home assistant view into the configuration view intermittently. Not sure exactly what happens here, but it could be that the connection to HA is clunky or something, and then the default is to go back to settings.

Usually I guess this does not matter much, but in kiosk mode it kind of defeats the purpose. In my case it is not a huge issue, since this is only used as a wall display and I can press the "Dashboard" button to get back, but nevertheless does not give a good UX.

=> Could there be a way to set WallPanel to retry "indefinitely" instead of reverting to config, and then maybe some other way to get to config if needed?

**Comment by thanksmister** [comment]
You need to provide the version of the application you are running.  We have not added any "kiosk" features current non pre-release versions of the application.  The only feature we have added in the newest pre-release is the ability to set the app as the home app.  I assume you are using an older version of the app.   Also please explain what you mean by kiosk mode, thanks.

**Comment by Din-BH** [comment]
> You need to provide the version of the application you are running. We have not added any "kiosk" features current non pre-release versions of the application. The only feature we have added in the newest pre-release is the ability to set the app as the home app. I assume you are using an older version of the app. Also please explain what you mean by kiosk mode, thanks.

I am running WallPanel 0.9.3 build 4.

In essence what I mean with "kiosk mode" is a mode where the final rendered Home Assistant view is expected to be the only use for the device, keeping the user in the desired screen "forever". Any additional part about shaping the UI I believe should not be part of the WallPanel task, but rather of different customization engines in Home Assistant itself such as the frontend tweak _t0bse_ mentions, but the ask for WallPanel is to keep the user in the desired final view - basically avoiding moving out into configuration view etc since the end user is expected to be "whoever" rather than a dedicated user and should not really be messing with configuring the WallPanel app.

Hope this explains a bit better?

**Comment by thanksmister** [comment]
This is not possible without a terrible hack, you can look at fully kiosk as an example, they have implemented this, but it's not very appealing.   The best approach is to disable the device keys (back/home) and set the app as the home app.   There are apps in the play store to disable the hardware buttons or software buttons.   You can use the pre-release to set the device as the home app.   The pre-release also has a code screen which is used to prevent access the the settings.

**Comment by Din-BH** [comment]
Thanks, I will try the pre-release. I believe it will fulfil all my needs actually as I understand you explanation. My environment in more "friendly" than some other more hard-core "kiosk" environments, as I do not generally expect people to "do the wrong thing", rather I am more trying to make sure the wall panel shows what is expected at all times.

Big thanks for fast responses!
