### ISSUE TITLE
WallPanel Keeps Closing but is still running. 

### ISSUE THREAD

**Issue by fLyRhyTHeMz** [thanksmister/wallpanel-android#192]
Android tablet: Huawei Media Pad T5
Version: EMUI 8.0 & Android 8.0

Every so often, maybe after a couple hours, the wall panel app will quit to the home screen, but will still how up as running in the notification shade. It doesn’t look like a crash or anything but i cant figure out why. 

I’ve disabled the lock screen, screen timeout, enabled never sleep while charging in dev settings and turned off all power management for this app in the settings. 

It’s running a front end Lovelace UI for my HA setup but was working fine till a few days ago. 

I’m fairly new to android (my entire setup is iOS based) but this was just a spare tablet i had lying around and figured I’d put it to good use as a wall mounted tablet, so let me know if you need any logs or something, and perhaps where to find them.

**Comment by thanksmister** [comment]
This application has two parts, the app that draws the views you see when you run it and a background service that can be seen in the notifications.  It appears that the main app is either crashing, there is an event for your exact device in Firebase, which reports app crashes for WallPanel. 

```
Fatal Exception: java.lang.OutOfMemoryError
Failed to allocate a 992 byte allocation with 528 free bytes and 528B until OOM, max allowed footprint 536870912, growth limit 536870912
```

Your tablet seems to have memory issues, so the app is probably getting closed by the system.  I could recommend that you try the legacy version fo WallPanel and see if this fairs better than the current one.  I can't really know for sure, but it could be resources used for MQTT messages that have changed recently, or maybe the app is using more resources due to rendering your Lovelace UI.

**Comment by fLyRhyTHeMz** [comment]
You were right. I played around with the app a little more and remembered i had turned on the rest API & mqtt options a few days prior as i wanted to mess around with them a little. Turned both of those off and everything works perfectly. Also figured out a workaround to get device data into HA. Just install the official HA app and enable the background processes permissions. This publishes device data to HA (battery, location, etc) even without having opened the app. Thanks for the help. Ill mark this as closed.
