### ISSUE TITLE
Top & side menu do not render properly

### ISSUE THREAD

**Issue by bverkron** [thanksmister/wallpanel-android#215]
**Describe the bug**
Top & side menu will not render properly after a certain point even when the app is refreshed. Navigating around the app causes the menus to "smear". Refreshing the app does not help. Clearing cache in settings does not help. Fully resetting the app worked but then the problem came back a day or two later. Have not experience this in any other browser / app yet (Brave on the tablet, Fully Kiosk, Safair or Chrome on iOS, etc) though testing in those has been limited.

Might be related to a UI change in 0.116.x did not experience this in 0.115.x. Currently on 0.116.3. I don't believe there have been any OS updates on the tablet between it working and not working.

**To Reproduce**
Use the app for a while with HA 0.116.x?

**Expected behavior**
UI renders as normal.

**Screenshots**
Default view when app is loaded
![Screenshot_20201012-085817_WallPanel](https://user-images.githubusercontent.com/19174503/95771290-a4293800-0c6f-11eb-8b0d-086fea23c30a.jpg)

After side menu is toggled out. Notice the smearing in the menu title like it's being stretched off screen to the left.
![Screenshot_20201012-085828_WallPanel](https://user-images.githubusercontent.com/19174503/95771341-b6a37180-0c6f-11eb-87bc-01bd7b4ab54d.jpg)

After swiping up part way (scrolling down the dashboard page essentially). Notice the smearing in the top and side menus.
![Screenshot_20201012-093040_WallPanel](https://user-images.githubusercontent.com/19174503/95771405-d76bc700-0c6f-11eb-98e2-7ed6db874d6e.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Tab A 10.1 (2019)
 - OS: Samsung OneUI 2.1
 - Browser: WallPanel
 - Version 0.9.3

**Additional context**

**Comment by thanksmister** [comment]
Your ability to render html depends entirely on your device and its version of WebView (not related to Chrome browser).  Some devices cannot render html and there is nothing that can be done because the application does not read or manipulate your html to render it, it relies on Google WebView component to render html.   You can either change the HTML of the page you are trying to render or try to update your version of the WebView component.  This is also a duplicate, so closing for now.
