### ISSUE TITLE
Constantly going to white screen and relaoding dashboard

### ISSUE THREAD

**Issue by kampto** [thanksmister/wallpanel-android#218]
Samsung Galaxy Tablet-A  The URL is sharptools kiosk dashboard.  It loads then within 10sec the screen goes white for a few seconds and reloads dashboard then repeats continuously. I disabled motion detect, no improvement.   Dashboard loads and works fine in chrome. Lot of free memory on the device, only wall panel is open.

Android 7.1.1
Tablet SW is up to date.
Wall Panel version less about 2 months old

**Comment by thanksmister** [comment]
This is upstream issue, WebView (not Chrome) does not seem to properly render the webpage.  This is out of scope for the application to address.  You can install a new version of WebView for your device or use a different webpage.  Working with Chrome is irrelevant since Android applications use WebView to render web pages, not Chrome.
