### ISSUE TITLE
Use built in android screensaver

### ISSUE THREAD

**Issue by tungmeister** [thanksmister/wallpanel-android#222]
I'd love the option to use the built in system screen saver functionality. This would mean being able to use any third-party screen savers giving the ability to access google photos etc.

**Comment by thanksmister** [comment]
That’s not a feature we need to integrate, just turn off the screensaver in the app and use Daydream.  It doesn’t need to be integrated with the app.

**Comment by tungmeister** [comment]
the problem with that approach is that I have to let android manage the display timeout and also the screen doesn't dim as it would when using the built in settings, unless I'm missing something?

**Comment by thanksmister** [comment]
There is no other way to integrate the Android devices screensaver.  It must be setup and used through the device.  It will dim your screen better than the application can since it has full control over the Android device.   In my opinion it is the best option for screensaver, the device does not have the ability to duplicate its perfromance.

**Comment by tungmeister** [comment]
understood, thanks.
