### ISSUE TITLE
Google Photos on Screensaver

### ISSUE THREAD

**Issue by diogo-madeira** [thanksmister/wallpanel-android#244]
It'll be a nice feature to show my google photos on the screensaver.

**Comment by zoujian019** [comment]
me too

**Comment by thanksmister** [comment]
I think this has been requested already, please check the issues.

**Comment by thanksmister** [comment]
I think a better idea would be to have a screensaver feature that loads a webpage from a local network that can host whatever images you want and be updated.

**Comment by etxttul** [comment]
I almost managed to do this with BETA version https://github.com/thanksmister/wallpanel-android/releases/tag/v0.9.4.9
I made a script with mqtt.publish {"url":"https://photos.google.com/photo/xxx"}
Then a delay, 
then a second mqtt.publish {"url":"https://photos.google.com/photo/yyyy"}
and so on.
The first time I had to go to the screen and log on to google, the it work, The first time I sent it to the wall panel I had to go there to log on to google the it worked even when after I restarted.

It is even quite nice, the first time loading it takes time, but the second time it is in the cashe and loads fas and nicely.

The problem is that in HA you can't can't call a script from within the same script, well you can but it just don't happen. This is kind of a good thing. If you could call a script from within the same script, you need some sort of way to break out of it.

A loop and loop break functionality in HA would do the trick. I believe I can come up with quite some scenarios more than wall panel that would need that.

**Comment by etxttul** [comment]
Hi, Again, I have to correct myself, it is possible to do loop in HA and break out of it, just use repeat in the script. please see.
https://www.home-assistant.io/docs/scripts/#repeat-until
This makes completly posible to do google photos, screen saver. I did a quick and dirty test and it works. There is a small glitch when changing picture, but with a bit longer delay than I have between pictures it should be acceptable.

**Comment by thanksmister** [comment]
Still seems a bit like a hack.  We have a ticket request to do local photos (on device) as a screensaver feature.    In the Alarm Panel app we have a web page screensaver, which loads any webpage a user would like to use as the screensaver.  The webpage could rotate through images, but it would need to be public or hosted on the HA server web folder.

**Comment by etxttul** [comment]
Hi, I now completed my automation for this, yes it is a hack. It work but have some issues. Firstly when loading a new picture, there is a fraction of a second of white screen between the pictures. I could live with this setting the timers quite long, meaning showing the same picture longer. The main problen is breaking out of the "sceensaver" going back to HA, this requires a complete reload of HA home screen, which takes some annoying seconds in my setup. I will stop this automation solution trial, mostly because I'm a lousy photographer and have no pictures good enough and prefer googles, proffesional picture where you don't know whats coming next :-)

**Comment by thanksmister** [comment]
A solution would be to create your own webpage and host in the HA public web server folder.  You can add whatever images you want and use the webpage screensaver feature to display it.
