### ISSUE TITLE
Web page always reload when screen wakes up (v0.9.3-beta.6)

### ISSUE THREAD

**Issue by BoneheadFraggle** [thanksmister/wallpanel-android#246]
**Describe the bug**
Webpage is reloaded each time the screen wakes up

**To Reproduce**
1. Configure WallPanel to use Camera, Motion detection and Wakes Screen
2. Prevent Sleep and all other Screen related options = Off
3. Let the phone turn off the screen
4. Wave in front of it
5. It wakes up and reloads the page

**Expected behavior**
v0.9.3-beta.4 and previous versions doesn't reload.
It is a much nicer experience to just see the dashboard rather than a page that reloads first each time the phone wakes up.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: OnePlus One, Nexus 6p, Sony Z3
 - OS: Android 8, 10, 11
 - Browser Stock browser

**Additional context**
I just love the new option to use as Launcher and Home Assistant Auto Discovery. Super nice!

**Comment by thanksmister** [comment]
I tested this on a Pixel 2 device.  I turned on the camera, then face detection and wake screen on face detected.  I then used the power button to turn off the screen.  When my face is detected the screen awakes but I do is not reloaded.    I did not test this for a length of time greater than 1 minute.   

I verified that we only reload the page automatically under two circumstances. The first is if the settings are "dirty" and user returns from the settings page.   The second is when the dashboard view is first loaded or recreated.   If for any reason the application main view is closed while the screen is off, the app will reload the webpage because the view must also be recreated.  My device does not close the activity so its not refreshing the url upon opening the device again using face detection. 

If you look at the code, the method `onCreate` will load the web page.  In Android, `onCreate` is part of the activity lifecycle and is only fired if the activity is created (as opposed to restarted or resumed).   We handle settings changes on the `onStart' method, but check that settings are "dirty" before reloading the page and only if the dashboard url has changed.   The app has always used the `onCreate` method to load the web page, the `onStart` method is new, but again we check if the settings are dirty before reloading the webpage. 

So far, I cannot reproduce the behavior you outlined on the devices I have.

**Comment by thanksmister** [comment]
One thing I did not mention, my phone has the device screensaver active, but this also works when both locking the device with the hardware button pressed or allowing the device to go into sleep mode using the device's built-in screensaver.   I suggest you retest this and see if perhaps your device is closing the activity when device lock is active (turning off the screen).   Maybe you are running other background processes so the app is closed as part of the normal garbage collection or another app is interfering with the functionality.

**Comment by BoneheadFraggle** [comment]
I just realised that I ran v0.9.3-beta.5. Updated to v0.9.3-beta.6 and now it wakes up without reloading as usual.
Strange since it seems nothing has changed, so maybe it was something else in my etwork yesterday. Anyway it works fine with v0.9.3-beta.6 so I'll just close this!
