### ISSUE TITLE
Add URL Screensaver Options

### ISSUE THREAD

**Issue by YorkshireHillbilly** [thanksmister/wallpanel-android#250]
Add the option of a URL Screensaver for use with DAKboard and other internet feeds such as aircraft tracking or news channels.

**Comment by DrChopsMD** [comment]
Yes this feature would be very useful as a screensaver.  Thank you for considering it.

**Comment by thanksmister** [comment]
I think we should combine this with https://github.com/thanksmister/wallpanel-android/issues/244 to improve screensaver options.  I know that using one's own photos has been requested many times and this ties into loading external URL's because the URL could be for hosted or private images (like from HA public folder).

**Comment by theoracle09** [comment]
I just came across Wall Panel and it looks like the best solution for Fire tablets right now. I also would like to have the capability to choose image source. I host my own Next Cloud server and have a ton of hiking and nature pics that'd be sweet to display on the screen saver. I haven't peeked at the source yet, but would be willing to help test or something to get this feature rolling.

**Comment by thanksmister** [comment]
We don't support image sources, but we do support webpages.  You can make your own hosted webpage, or use Home Assistant public server to host whatever webpage you want with the image you choose, that is the best solution.
