### ISSUE TITLE
[BUG]Last version can't be updated in HD8

### ISSUE THREAD

**Issue by dotanshai** [thanksmister/wallpanel-android#279]
**Describe the bug**
When trying to update via Google Play store.  There is a message in red saying:
"This app isn't compatible with this device anymore. Contact the developers for more info."
![Screenshot_20210606-233742](https://user-images.githubusercontent.com/42491156/120939480-fc420c80-c720-11eb-97fe-86d1cd2b5242.png)

**To Reproduce**
Just try to install in Amazon HD8. 

**Smartphone (please complete the following information):**
 - Device: Amazon Fire HD8 (8th generation)
 - OS: Fire OS 7.3.1.9
 - Applicaiton version : latest WallPanel Release

**Comment by thanksmister** [comment]
Have you tried to install from the Amazon store?    Fire  OS 7 is based on Android Pie (https://en.wikipedia.org/wiki/Fire_OS).   Android Pie is Android API level 25.  Wallpanel supports minimum API level 19 and has not changed.   Perhaps this is some issue with Google Play and Fire tablets.    It might not recognize that your Fire OS version is a viable version for Android 19 and above.  I can't say since technically there seems to be no issue that would prevent it being compatible with Android API level 19 or above devices.

**Comment by dotanshai** [comment]
Thank you for your detailed response. I've just installed WallPanel and re-install from Amazon App store. Everything works. My problem is solved. Didn't know that there was a version of WallPanel in Amazon app store 10x.
