### ISSUE TITLE
Some webpages are not supported on older devices

### ISSUE THREAD

**Issue by lezlikov** [thanksmister/wallpanel-android#288]
**Describe the bug**
When I launch the application, after entering the login / password, I again get a blank white page with a blue bar at the top. What am I doing wrong?

**To Reproduce**
need help 

**Smartphone (please complete the following information):**
 - Device:  Samsung SM-P605
 - OS: Android 5.1.1
 - Applicaiton version v.0.9.5 Build 6

**Comment by thanksmister** [comment]
Nothing is wrong, the web page you are viewing is not supported by the WebView component of your Android version.  Either try a different web page or try to update your WebView component.   If you are trying to display Home Assistant with LoveLace, it's probably the issue because some components won't work on older versions of WebView.   You may want to try as simpler desktop or Tileboard.

**Comment by lezlikov** [comment]
Thank you. I will think about it

**Comment by 36grad** [comment]
In case anybody else comes across this "issue", I was able to resolve this on an old Android 6 tablet exactly like described [here](https://support.honeywellaidc.com/s/article/How-to-update-Android-Webview).
1. Disable Chrome
2. Update Android System WebView from Google Play Store
3. (Reboot) - not sure if needed
4. (Enable Chrome) - not sure if needed
5. Home Assistant's Lovelace Interface shows up in Wallpanel.

Note: tested with [v0.9.5-beta.9](https://github.com/thecowan/wallpanel-android/releases/tag/v0.9.5.9)
