### ISSUE TITLE
Panel goes to background after few hours

### ISSUE THREAD

**Issue by Marooned-MB** [thanksmister/wallpanel-android#36]
**Describe the bug**
Panel goes to background after few hours. The icon in notification area shows that it's running, it's just not a foreground app. On foreground is whatever was there before WallPanel, so usually launcher.

**To Reproduce**
1. Run WallPanel
2. Wait a few hours (leave overnight is the simplest approach)
3. Wake the screen (I use wake on motion using front camera)
4. See panel not visible

**Expected behavior**
Panel still as a foreground app.

**Smartphone (please complete the following information):**
 - Device: TB Touch Ignis 8
 - OS: Android 4.2.2
 - Browser: stock browser

**Additional context**
I've tested few different applications on the same device and WallPanel was the only one that goes to background. Others app were foreground until I manually switched them, so there is something strange with this particular app.
I've tested different pages (even google.com) to make sure it's not a particular page causing this strange behavior.
I've also tested WallPanel on my phone (Samsung S5 with Android 5.0) and it was fine (left as foreground overnight), so in my case it's only this app on one device which makes it harder to debug and fix.

I understand you are not supporting such old Android (per my last issue when you created legacy fork) but maybe you could help with this one more time? This issue is quite frustrating as I have to bring back WallPanel few times a day to see displayed data.

**Comment by vitalykorolev** [comment]
The same is happening on Amazon Fire 7.

**Comment by thanksmister** [comment]
@vitalykorolev Amazon devices have no screen saver ability such as standard Android Daydream, so you would have to run the application with the option to prevent the screen to sleep or use another application to act as a screensaver.   By default the application does not keep the screen awake because this would burn the screen, so it relies on the screen saver to be in shallow sleep, but without that ability, Amazon devices go into deep sleep and kill applications.

**Comment by thanksmister** [comment]
@Marooned-MB Are you running the legacy version of the application, because you are reporting the issue on the current version.

**Comment by vitalykorolev** [comment]
@thanksmister I think I misunderstood the original report. I don't use the screensaver and I just keep the screen on all the time. I think in my case the issue is related to SSL handling.

**Comment by thanksmister** [comment]
Have you updated recently?  I added some logic to handle SSL.  I’m going to add a screen saver at some point to the app for Amazon tablets.

**Comment by Marooned-MB** [comment]
> Are you running the legacy version of the application, because you are reporting the issue on the current version.

I'm running regular version, just stopped updating at the last working version v0.8.4 build 1

>  I have no crashes reported for the latest version of the application.

It's not crashing. It just goes into background as if I hit the home button or switch to the last running app.

**Comment by thanksmister** [comment]
@Marooned-MB it still might be crashing, but since that version is so old, I can't tell if I fixed it or not since then.   There is no way to address this issue because you are not on a version that I can test to duplicate the issue.   Plus, if I did fix the issue, you would still have to update to get the fix.  I am not able to work on the legacy version or do bug fixes without a lot of effort.   So... not sure how I can help other than recommend you run the legacy version by side-loading it.

**Comment by Marooned-MB** [comment]
But as I understand, legacy version is exactly as this version v0.8.4 build 1? It's more or less a frozen tag, so they do not differ?

Am I able to install a particular toolchain to compile recent code every time you do some fixes and produce .apk that will run on my machine? So containing working Crosswalk? Thanks to that I won't bother you with support you can't provide plus I can tell if the recent code has this particular issue.

**Comment by thanksmister** [comment]
The difference is that I can test the legacy version, verify the issue on my older tablet and if its something simple, I may be able to address it.  I can't fix an older version of the v0.8.4 build 1 and update it, I have only the possibility of updating legacy version.    You can install Android Studio (new version) and install legacy version.  It will work as long as you do not update the target SDK version in the gradle file.    Crosswalk is another library entirely, its no longer being worked on.  The only thing that happened is newer versions of the Google SDK or toolchain no longer work with Crosswalk because its so outdated.

**Comment by Marooned-MB** [comment]
Ok, got it. So I'll install legacy in a minute and leave it overnight to check if the issue exists. If so, I'll open the issue on legacy repo. Thanks for clarifications and your great work!
I'll also go with the Android studio as a side approach.

**Comment by Marooned-MB** [comment]
After almost 24h I can confirm that legacy version (v0.8.4 build 7) does not have this issue so it was either fixed between build 1 and 7 or different toolchain help solving this problem. Either way, I'm closing this issue.

**Comment by olalid** [comment]
I too have this or a similar issue. On my device (Lenovo 7 inch tablet with Android 5.0.1) it seems the WallPanel just will not stay active for more than a day or so, when I wake my device up the first thing I see is WallPanel settings page, so the app has somehow reverted back to the settings page and then the screen goes to sleep after a while.
I have looked at all settings I can find in the device, screensaver, sleep modes etc, and I have everything disabled as far as I can see.
WallPanel is set to always keep the screen active.

**Comment by olalid** [comment]
In case this helps someone else, the problem I described above seems to be solved by turning off automatic updates in google play (fingers crossed, but for now the app has been working for longer than ever before). Seems that every time that update process is run on the device wallpanel will for some reason go to the background or something similar.

**Comment by jackwilsdon** [comment]
Sadly my Amazon tablet doesn't have the Google Play store, but I'll try disabling updates for the Amazon Store (if possible) and report back if anything changes.

**Comment by Madseason41** [comment]
> I seem to be having this issue on v0.8.5-beta.6 with a Kindle Fire 7 (7th generation, 2017) on Fire OS 5.3.6.4.

Same here. I switched over to Fully Kiosk and its pretty decent. But I really like the mjpeg camera streaming of wall panel so I thought I would give it another go. I just installed the legacy version and have the browser selection set to automatic. Figured I'd give that a go, if it doesn't work then I'll try the crosswalk selection.

**Comment by thanksmister** [comment]
After testing for several weeks I have concluded that the camera on the Amazon Fire devices is the cause of the application going into the background. 

This means that their is a limitation when using the application on those devices when using motion, face, QR or MJPEG streaming for long periods of time.

There is no fix or work around. FireOS is a custom build of Android and the tablets and I believe there is something that closes applications that use large resources at certain times.  This issue is already closed because it can not be addressed.

**Comment by Madseason41** [comment]
Yeah I figured it was the camera that was causing my issues. 

Just out of curiosity, and I understand if it’s a no, but is there a way to implement using the camera to get around the fireos limitations?

I believe Fully Kiosk uses a snapshot method.

End state for me would be a method that would allow linking with something like motioneye.

**Comment by jackwilsdon** [comment]
That makes sense @thanksmister, thanks for at least confirming the cause :+1:

**Comment by thanksmister** [comment]
Yeah, there is a possibility to use only a snapshot feature, but that takes some time to implement.  You are welcome to add a feature request.
