### ISSUE TITLE
Display security/certificate errors or use the Android certificate store to validate certs.

### ISSUE THREAD

**Issue by Twanfox** [thanksmister/wallpanel-android#7]
Using simple authentication (http_password) with HomeAssistant and a valid LetsEncrypt certificate on HA's standard port (8123), WallPanel does not connect, does not indicate any error, and only displays a blank screen. Using Chrome on the same device will connect to the page successfully from the same network presence. Main page or subpages have same behavior. Use of automatic browser engine and the loading message disappears quickly without complaint and with blank screen. Use of Crosswalk project engine prompts with Request Denied to Security and net::ERR_INSECURE_RESPONSE

No observable logs to provide.

**Comment by thanksmister** [comment]
I can connect to https sites (https://www.google.com) without any issues using the native browser or crosswalk.   The "Request Denied to Security and net::ERR_INSECURE_RESPONSE" you get with Crosswalk it points to a certificate with an incomplete certificate chain specifically with LetsEncrypt certs. More information here: https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/187.   I am testing with login credentials, it's possible that when I added cache clearing (due to another users feature request).

**Comment by thanksmister** [comment]
I am able to login and view HASS using the password with simple authentication.  I don't have LetsEncrypt because I only access my HASS on my own network.  However, I am able to connect to secure sites using valid certificates.   Are you perhaps trying to access the local IP address of your HASS instead of the outside address which you use to access HASS outside your domain?   This seems to be the issue, perhaps the Chrome browser is more forgiving than the WebView component used in Android or CrossWalk.   But so far I am not able to reproduce the issue without of course duplicating your exact setup.

**Comment by thanksmister** [comment]
I can investigate that possibility but working with WebView is a major pain and takes time.  If you know of a way to make WebView bubble up security errors or use the certificate store of the Android device, that would help with time and limit my need to investigate.   I will change this to a feature request.

**Comment by thanksmister** [comment]
I am not sure what you mean by this part:

> Of course, now I cannot load the custom panels that contain javascript in them, but that doesn't relate to a https/blank screen scenario.

**Comment by Twanfox** [comment]
I have a few custom panels using the Floorplan for Home Assistant
framework. When I try to view that custom panel within WallPanel, I get the
following error. My assumption is to a javascript dependancy not met within
the browser in use in WallPanel. However, as I stated, with the certificate
alterations I made on my HA environment, I can view the HA web pages with
the exception of the Floorplans. So this is a different issue all together.

https://homeassistant:port/static/custom-elements-es5-adapter.js:13:615
Uncaught TypeError: Class constructor HaPanelDownstairsPlan cannot be
invoked without 'new'

**Comment by thanksmister** [comment]
Can you update your WebView component from Google Play?

**Comment by Twanfox** [comment]
My tablet (S3) is autoupdating its apps, running Android 8. It is also using Chrome 68 which has the Android System Webview component built in.

**Comment by thanksmister** [comment]
I am talking about this component: https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en_US.  This is installed separately on my Google Pixel running Android 8.   This component is driving the content when using the WebView component in Android applications.

**Comment by Twanfox** [comment]
I understand what you were asking. I cannot install or update or enable that component (currently disabled on my device). Quick research indicated Chrome took over that functionality, and looking in the developer options for my device, that is the case. I cannot select the Android System WebView component. Chrome is the only app serving those requests that can be selected. It is up to date.

**Comment by thanksmister** [comment]
I assume then you are using the latest WebView component already.   If there are incompatibilities with the JavaScript, I can't address them with WallPanel because this is part of the WebView component.  I think I have found a way to show and ignore security errors and will add this to the next release today.  Maybe that will resolve some of the issues with the SSL certificates.    There is a paid application that you may wish to try if you can't get WallPanel to work, they have done extensive work on the app to make it compatible: https://www.ozerov.de/fully-kiosk-browser/

**Comment by thanksmister** [comment]
I have released 0.8.2-beta.8 which contains error handling for SSL certificates, let me know if this helps.

**Comment by thanksmister** [comment]
I think this might be an issue for Floorplan, to make it more compatible with different (and older) browsers.   It might be a simple JavaScript issue that can be fixed to increase compatibility.
