### ISSUE TITLE
Please can we get Wallpanel to work with the HA Stream Component?

### ISSUE THREAD

**Issue by MikeMannox** [thanksmister/wallpanel-android#72]
Please can we get Wallpanel to work with the HA Stream Component?

https://www.home-assistant.io/components/stream

Many Thanks

**Comment by thanksmister** [comment]
What does that even mean?   The application is meant to show a website or home automation platform, its up to you to configure what you show on your platform webpage.

**Comment by MikeMannox** [comment]
I think a cooler tone may be a better approach to making friends, at the moment, you are not approachable and frankly quite rude. 
But I was thinking that maybe the cameras part of the app could be adapted to stream HLS or a suitable format for HA.
It could even broadcast a url/path using MQTT.
I'll leave this up to you and your "creativity"

**Comment by akasma74** [comment]
> I think a cooler tone may be a better approach to making friends, at the moment, you are not approachable and frankly quite rude.

I didn't notice any particular rudeness in this case (maybe I'm a rude person myself?), but in general I do agree with the second part of your statement ;)

Actually, after getting a few similar responses to my issues recently and stumbling upon your response I thought "Maybe it's time to make move?"

Fortunately, there are other similar projects out there, much more popular - have a [look](https://community.home-assistant.io/t/ariela-home-assistant-android-client/67519).
One of my HA friends uses it and quite happy with it.
I haven't tried it yet, but the topic speaks of itself - it's well alive and well supported.

Rant over ;)

**Comment by thanksmister** [comment]
There is a set way to file a feature request.  The application is not a replacement for Home Assistant. It’s for displaying home platform websites.   

If there is a feature that you think you would like, then you also have the option to do a pull request for that feature.   It’s an open source project and that is the best way to contribute.

If you feel that your feature isn’t getting the attention you think it deserves, again the way to contribute is to do a pull request and contribute your time and code to the project.   

I’d you don’t agree with the way the project is progressing  or feel that your contributions to the project are not respected, you have the option to fork the project and make your own .

The contributions people make the most often are feature requests  and bugs.   Those are fine as well, but try to follow the project guidelines for submitting them.

Nobody should feel that they are not heard but ultimately it’s me doing the work on this project and it’s my choice what requests I feel should be on the road map.   

There are also other projects available for HA and home automation platforms, there are also paid applications that have similar functionality to this application like Fully Kiosk Browser.  This application is not in competition with other projects, it’s a contribution to the IoT community which I’ve taken upon myself to do.  The project is itself a fork of another project.

Don’t confuse free open source software with some paid services or purchased product.  It’s run completely by volunteers and this project page isn’t a customer service portal for complaints or rants.  There is no place for that behavior.  It’s not a social media platform it’s a project platform.  Contribute in a constructive way, follow the guidelines and when ever possible contribute with code.

There are plenty of projects that will not even accept a sing feature request or even comment without completing the proper form and adherence to the project guidelines.  I may have been to lax and the amount of features and “me too” comments have piles up.

I will do better to make requests follow the guidelines so that users can contribute without feeling unheard or me having to do follow up questions.

**Comment by thanksmister** [comment]
@MikeMannox file a new feature request with the information. Thanks

> But I was thinking that maybe the cameras part of the app could be adapted to stream HLS or a suitable format for HA.
> It could even broadcast a url/path using MQTT.
> I'll leave this up to you and your "creativity"
