### ISSUE TITLE
Opening dashboard dims screen

### ISSUE THREAD

**Issue by halfbaked** [thanksmister/wallpanel-android#82]
**Describe the bug**
I adjust the tablet screen brightness to max, I then open the wallpanel app. If I'm in the settings menu, all is fine, but once I open the "dashboard" the screen dims right down to min. In an attempt to remedy, I toggled on/off pretty much all the settings(including turning off the camera) but none fixed the issue. 

The issue was not there when I first installed the app, and my fix in the end was clear all the app data.

**To Reproduce**
I'm afraid I don't know how I caused the issue, I can only speculate it was some combination of settings changes.

**Expected behavior**
the screen does not dim everytime I access the dashboard

**Smartphone (please complete the following information):**
 - Device: Fire HD 8 
 - OS: Original Amazon provided
 - Browser: stock browser
 - Version 7

**Comment by HFsi** [comment]
In my case, was an update

**Comment by thanksmister** [comment]
The brightness setting is a strange beast at the moment.  The way you set or reset the brightness is to adjust the device brightness before opening the app settings.  When you open the settings, we read the current system brightness and save this value as the default value when using the brightness setting.   It would be nice to have a slider in the settings screen to adjust and test the desired brightness level.

**Comment by HFsi** [comment]
Like @halfbaked said, prior to 0.86, I didn´t have the problem.
Maybe this could give you some idea

**Comment by thanksmister** [comment]
v0.8.6-beta.3 doesn't exhibit any issues.  As @halfbaked has stated "my fix in the end was clear all the app data."  A new install might also work.  If the brightness settings do not work with a particular device, then my recommendation is to not use them.   

In addition to not using the Screen Brightness setting in the Camera Settings section, you need to turn off the brightness permission in the device settings.  This varies depending on the device, but you would normally enter your device Settings go to Apps then select the menu item (gear icon) from the menu which is configure apps permissions.   

This is where you will find the app permissions for modifying the system settings.   Select Modify system settings then select WallPanel app and turn off the the Allow modify system settings, this will disable the app from adjusting the screen brightness. 

If you can't not locate the system settings, then the easiest way is to uninstall and reinstall the application, then do not give it permissions to change your devices brightness settings when asked during the initial settings.   Modifying the system settings permits behavior that may not work on all devices and so this feature may not be something each users should use. 

Instead of using the screen brightness feature, I recommend using Daydream or another screen saver option of the device.

**Comment by halfbaked** [comment]
Sounds good @thanksmister  -  I've not played with the brightness settings of the wallpanel since resetting the data and no issue. Good enough for me anyway. Thanks for your hard work.
