### ISSUE TITLE
Screen brightness goes to 1% upon running WallDisplay after latest update (v0.8.6 build 6)

### ISSUE THREAD

**Issue by MarkHofmann11** [thanksmister/wallpanel-android#85]
Upon running the latest WallPanel (v.0.8.6 - build 6), screen brightness goes to 1% immediately.  Closing app, re-setting brightness to 100% in Settings on Android Tablet (tab-a) - then running Wallpanel again takes it back to 1% immediately.

build 5 doesn't have this issue, but selecting front camera still displays the rear camera on that build.

Running build 3 which works fine on screen brightness and camera selection.

**Comment by thanksmister** [comment]
To sat the screen brightness of the app you need to set the device brightness to the desired level then go into the app brightness and turn on the screen brightness setting, if it’s not already active.  Otherwise disable the brightness setting in the app, adjust your device settings to the desired level and return to the device to activate the brightness setting.   There is no manual setting to adjust brightness so it takes the brightness value at the time you enter the settings or turn in the setting.

**Comment by MarkHofmann11** [comment]
First I set the brightness to 100% on the system/Android.  Once I run Wallpanel it immediately changes the brightness to 1% before I do anything further.  I tried to disable the brightness setting in the screensaver, but it keeps changing the brightness to 1% as soon as Wallpanel runs.  Then it is very difficult to see the screen to make adjustments unless in a really dark room.  I don't want to disable the clock screensaver which is really nice.  Just trying to keep it from immediately going to 1% upon executing Wallpanel.  

Should I be able to switch back to the Android system settings and re-adjust to 100% while Wallpanel is still running?  Maybe that is how I can do it so it retains the proper level?

**Comment by thanksmister** [comment]
Go into your device settings, go to Apps then go to WallPanel, at the bottom of the App info there is a advanced section with Modify system settings.  Just remove the permission.   This is for a new device, so if you are on an older device go into Settings, then Apps, then select the icon in the menu that looks like a gear, you will see the Modify system settings.  Remove the permissions there for WallPanel.

**Comment by MarkHofmann11** [comment]
I see where the application permission are under settings/apps.  It won't let me turn any of them off, however.  No toggle or way to do it on a 7" Tab-A from what I can tell.  Somehow, the same problem just happened on the older version v0.8.6 build 3.  Each time I run it now, it changes my brightness to around 10-15%.  Should I try uninstalling to remove permissions and revert to pre-dimming screensaver?  I like that feature, just seems to somehow want to dim my screen upon running Wallpanel for unknown reasons.  Not sure if re-installing will allow me to select which permissions, so I can deny screen brightness for the time being.

**Comment by MarkHofmann11** [comment]
BTW, build #3 was working fine until last night.  I'm thinking the clock screen saver crashed or something, thus keeping my reduced screen brightness as the default setting.  If I go to settings and change it back to 100%, wallpanel will revert it back to the 10-15% as soon as I run it.  It is like it holds onto the last known screen brightness setting.

**Comment by thanksmister** [comment]
You can try the new beta release https://github.com/thanksmister/wallpanel-android/releases/tag/v0.8.6.7.  I have totally redone the brightness behavior for the application and allowed the device to be returned to automatic brightness control if the setting is disabled.  There is also a new brightness capture button to manually reset the brightness level from the settings to the current device brightness.   Brightness can also be controlled via MQTT commands (see the updated documentation for full description).

**Comment by MarkHofmann11** [comment]
Thanks!  Really like the new screen brightness configuration design!  Been running the latest build for (2) days now, but so far so good.  

One thing I don't understand is why this morning my Tab-A was off due to running out of power.  It is plugged in, so that should never happen.  That never happened before - but could have been an anomaly.

**Comment by MarkHofmann11** [comment]
It appears the screen brightness doesn't dim when the clock screen saver is on, just noticed that.

**Comment by MarkHofmann11** [comment]
Walpanel will Auto start, but not launching the dash url.  Have to manually hit dashboard on reboot.

**Comment by thanksmister** [comment]
I don't know why your device battery drained, it could be a number of things.  I would check your devices power drain to see if there are other apps running.  WallPanel will draw power especially if the screen is bright.  

So if you were not using Daydream, you need to turn on brightness control, and use the screensaver feature.  Be sure to set the % of dimness while the screensaver is on to as low as high as possible.  Initially its 0%, which means no dimming occurs. 

If you find an issue or bug, please make a separate report rather than updating this issue.  We want to be able to clear issues not keep them open as a running discussion thread.
