### ISSUE TITLE
Auto brightness forced on even with screen brightness permission off

### ISSUE THREAD

**Issue by DarkFox** [thanksmister/wallpanel-android#94]
**Describe the bug**
Every time the app is started, as well as at regular intervals, auto brightness is turned on. This is an issue for devices that don't have light sensors, as it makes the brightness controls do nothing (Both the manual control, or trying to set it from Tasker). Turning brightness permission on or off in wallpanel, has no effect on this behaviour. It is especially bad as on my device, there's no setting to disable auto brightness, so you have to do it through a 3rd party app (like Tasker).

**To Reproduce**
1. Ensure auto brightness is turned off, and that brightness permission is off in Wallpanel
2. Open Wallpanel

**Expected behavior**
Auto brightness should not be touched, and brightness controls (either manually or through Tasker) should work as intended.

**Observed behavior**
The screen goes full bright and brightness controls stop working, due to auto brightness being turned on.

**Smartphone (please complete the following information):**
 - Device: Lenovo Tab 7 Essential (TB-7304F)
 - OS: Android 7.0
 - Browser: Chrome
 - Version: 74

**Comment by thanksmister** [comment]
You actually have to give the application permission to control the brightness.  So since it now has permission, it will adjust the permission.  To fix this, first go into the app and turn off the brightness in the settings, then go into the device settings and remove the permission for WallPanel to control the screen brightness.  

The app will no longer control your devices brightness in any manner.   If you just turn off permission, WallPanel will set your devices brightness control to automatic.    Removing the permission ensures the device doesn't have any control over the device. 

The special app permissions may be different depending on the device, here is a video of where it was located on my device.   You may have to dig around a big to find it depending on the device.


![Screenshot_1560642932](https://user-images.githubusercontent.com/142340/59557417-ed9c4100-8faf-11e9-8d5f-65de1cedc12d.png)
![Screenshot_1560642926](https://user-images.githubusercontent.com/142340/59557418-ed9c4100-8faf-11e9-9070-bf69101f603d.png)

**Comment by DarkFox** [comment]
Thanks for the workaround.

Though it still seems to me, that if the brightness toggle is turned off in the app, it shouldn't be touching the brightness settings.
