### ISSUE TITLE
After android reboot wallpanel starts before unit connected to wifi

### ISSUE THREAD

**Issue by elindse** [thanksmister/wallpanel-android#97]
### Is your feature request related to a problem? Please describe.
After android reboot wallpanel starts before unit connected to wifi.

I have WallPanel installed on wall mounted android unit which are connected to charger 24/7. If the tablet are connected to charger more than few days it stops taking charge and dies out. Today this is fixed by having the tablet automaticly reboot every night.

Using the WallPanel function for starting the app at reboot, it starts and tries to show dashboard before the unit is connected to WIFI. This results in a "can not connect"-site. Now I have to manually refresh dashboard each day..

### **Describe the solution you'd like**
Automaticly refreshing dashboard every X hours /
Automaticly refreshing reconnected to WIFI / 
App starts when reboot AND connected to wifi

### **Describe alternatives you've considered**
Using some sort of tasker, but should not be necessary?

**Comment by PeteCondliffe** [comment]
I have this issue too. using LineageOS on a Amazon Fire 7 the app loads very quick

**Comment by thanksmister** [comment]
I cannot change the app loading which means this is going to be an issue for some devices.  My only recommendation is to not have the app auto load on start or use something like Tasker to launch the application.

**Comment by pkatzu** [comment]
> I cannot change the app loading which means this is going to be an issue for some devices.

That's true. However, from what I can see, Wallpanel tries to connect to the url provied and if it fails because network interface is not up yet, it just stops.
Maybe it's possible to change the load process so Wallpanel makes several attemps to connect every 30 seconds (configurable or not, doesn't really matter I think) or so before giving up?
Just a thought, maybe it makes sense?

**Comment by thanksmister** [comment]
We can detect wifi connectivity on startup and delay loading the website until the connection is valid.   It does not require a timer because the device itself will message us on a callback the state of the wifi connection.   I will bump this to feature request if someone wants to take up this feature.

**Comment by pkatzu** [comment]
Even better so!
I'd love to help, but have zero knowledge in Android app development :\

**Comment by thanksmister** [comment]
This is no longer valid since we reconnect or refresh web pages on error or disconnect.
